name: Trigger auto deployment for acagithubcdciapiapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/acagithubcdciapiapp-AutoDeployTrigger-13a5eb23-5ba9-4775-a5c8-80ae94952224.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAGITHUBCDCIAPIAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acagithubcdciapicontainerregistry.azurecr.io
          registryUsername: ${{ secrets.ACAGITHUBCDCIAPIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAGITHUBCDCIAPIAPP_REGISTRY_PASSWORD }}
          containerAppName: acagithubcdciapiapp
          resourceGroup: ACA-GitHub-CDCI-Api
          imageToBuild: acagithubcdciapicontainerregistry.azurecr.io/acagithubcdciapiapp:${{ github.sha }}
          dockerfilePath: Dockerfile

     

