name: CI/CD to Azure Container App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t $DOCKER_REGISTRY_URL/ACA-GitHub-CDCI-Api:latest .
          docker login $DOCKER_REGISTRY_URL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_REGISTRY_URL/ACA-GitHub-CDCI-Api:latest

      - name: Deploy to Azure Container App
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: $DOCKER_REGISTRY_URL/ACA-GitHub-CDCI-Api:latest
          multi-container-config-type: "None"
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          region-name: ${{ secrets.AZURE_REGION }}
